vscode:
  extensions:
    - octref.vetur@0.32.0:03mwRhlVpWDul4qBChcVUA==

tasks:
  - before: printf "$wakatime" > ~/.wakatime.cfg
  - name: Dev Server
    init: |
      cd jonathan-treffler.de
      npm ci
    command: |
      cd jonathan-treffler.de
      npm run dev