name: Github Contributions Chart Download

on:
  schedule:
    - cron:  '0 */2 * * *'
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    
    - name: Download Contributions SVG
      run: curl https://ghchart.rshah.org/JonathanTreffler > githubContributions.svg
      working-directory: jonathan-treffler.de/static
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
        
    - name: Install svgcheck
      run: pip install svgcheck

    - name: Verify Contributions SVG
      run: svgcheck -v githubContributions.svg
      working-directory: jonathan-treffler.de/static
      
    #- name: Commit files
    #  continue-on-error: true
    #  run: |
    #    git config --local user.email "actions@github.com"
    #    git config --local user.name "Github Actions"
    #    git add -A
    #    git commit -m "Updated github Contributions Chart" -a
    
    #- name: Push changes
    #  continue-on-error: true
    #  uses: ad-m/github-push-action@master
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    branch: dev
