name: Lint

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      working-directory: jonathan-treffler.de
      run: npm ci

    - name: Lint JavaScript
      working-directory: jonathan-treffler.de
      run: npm run eslint

    - name: Lint CSS
      working-directory: jonathan-treffler.de
      run: npm run stylelint
